-- ⚠️ MIGRACIÓN NEUTRALIZADA A PROPÓSITO — NO RESTAURAR SU CONTENIDO ORIGINAL.
--
-- Esta migración abría `weekly_checkins` y `daily_handoffs` a la clave `anon`
-- con `USING (true)`. La clave anon viaja dentro del JavaScript del navegador y
-- es pública por diseño, así que cualquiera podía leer y modificar todos los
-- check-ins semanales del equipo —incluidos mood_score, feedback_text,
-- highlights e improvements— mientras la app les prometía en pantalla
-- "Solo lo ve Marian".
--
-- Origen del fallo (auditado el 2 de agosto de 2026): las políticas correctas
-- comprobaban el rol de admin contra `public.profiles`, que entonces no existía
-- en producción. Como la comprobación nunca podía funcionar, se sustituyó por
-- `TO anon USING (true)` como apaño. No fue descuido: fue un parche sobre una
-- tabla que faltaba.
--
-- Estado actual (verificado en producción el 25 de agosto de 2026):
--   - weekly_checkins solo permite leer y escribir el check-in propio;
--   - daily_handoffs se creó cerrada al navegador, solo service_role;
--   - toda la escritura real pasa por api/coach-weekly-checkin.js y
--     api/operational-data.js, que validan en servidor.
--
-- Se conserva el fichero con su timestamp para no romper el orden del
-- historial, pero vaciado: si alguien ejecutase `supabase db push` sobre una
-- base limpia, el contenido original reabriría el agujero.
--
-- El contenido original sigue en el historial de git si hiciera falta
-- consultarlo: `git show 8988327:supabase/migrations/20260417180000_coach_handoffs_checkins_anon_access.sql`

select 'migracion_neutralizada_no_reintroducir_acceso_anon' as nota;
