import { describe, expect, it, vi } from 'vitest'
import { createWodBusterCoachEventsHandler } from './wodbuster-coach-events.js'

const config = { enabled: true, individualCoachAccess: true, secret: 'local-test-secret', organizationId: '018f1f4d-7b6c-7d8e-9f10-111213141517', serviceKey: 'service-role', supabaseUrl: 'https://staging.supabase.test' }
function request(body = {}) { return { method: 'POST', headers: { 'x-evo-wodbuster-key': 'local-test-secret' }, body: { id: 'wodbuster-demo-001', type: 'trial.confirmed', coachId: 'javi', occurredAt: '2026-09-08T09:30:00+02:00', person: { reference: 'Caso de prueba A', phase: 'Clase de prueba' }, ...body } } }
function response() { return { statusCode: null, body: null, status: vi.fn(function set(code) { this.statusCode = code; return this }), json: vi.fn(function send(body) { this.body = body; return this }) } }
function unit(options = {}) { const recordEventImpl = options.recordEventImpl || vi.fn().mockResolvedValue({ created: true, event: { event_type: 'trial.confirmed' } }); return { recordEventImpl, handler: createWodBusterCoachEventsHandler({ createClientImpl: vi.fn(() => ({ kind: 'server-client' })), recordEventImpl, readConfigImpl: options.readConfigImpl || (() => config), requestIdImpl: () => 'request-one', nowImpl: () => new Date('2026-09-08T08:00:00.000Z'), logger: { info: vi.fn(), warn: vi.fn() } }) } }

describe('POST /api/wodbuster-coach-events', () => {
  it('registra solo un evento operativo autorizado', async () => { const app = unit(); const res = response(); await app.handler(request(), res); expect(res.statusCode).toBe(201); expect(res.body).toMatchObject({ ok: true, eventType: 'trial.confirmed' }); expect(app.recordEventImpl).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ source: 'wodbuster', person_id: null, idempotency_key: 'wodbuster-coach:wodbuster-demo-001' })) })
  it('permanece oculto hasta activar el acceso individual de entrenadores', async () => { const app = unit({ readConfigImpl: () => ({ ...config, individualCoachAccess: false }) }); const res = response(); await app.handler(request(), res); expect(res.statusCode).toBe(404); expect(app.recordEventImpl).not.toHaveBeenCalled() })
  it('rechaza orígenes sin clave, datos personales y pagos', async () => { const app = unit(); const withoutKey = response(); const personal = response(); const payment = response(); await app.handler({ ...request(), headers: {} }, withoutKey); await app.handler(request({ person: { reference: 'Caso A', email: 'persona@example.test' } }), personal); await app.handler(request({ type: 'payment.completed' }), payment); expect(withoutKey.statusCode).toBe(401); expect(personal.body.error).toContain('forbidden'); expect(payment.body.error).toBe('event_type_not_allowed'); expect(app.recordEventImpl).not.toHaveBeenCalled() })
})
